/**
 * @file symbol_NA.ld
 * @author Irdkwia & Adakite
 * @brief SND Stream Library C Edition
 * @details Port of SND Stream Library to C
 * @version 0.8.6
 * @date 2026-02-22
 */
FunctionUnk1 = 0x02002CB4;

SoundMemoryArenaPtr = 0x022A4E54;

EndHookStartBGM = 0x020198D4;
EndHookStartBGM2 = 0x02019970;
EndOfStartBGM = 0x02019AF8;
EndHookStopBGM = 0x02019B34;
EndHookChangeBGM = 0x02019C68;

HookCheckOverlayArm9 = 0x020B0C80;
EndHookSoundProcess = 0x0207103C;
HookChannel1 = 0x020743EC;
HookChannel2 = 0x020743F4;

SetChannelVolume = 0x0207CA24;
SetChannelGlobal = 0x0207CA6C;

ChannelsStruct = 0x022B7A30;

TMR2 = 0x04000108;