/**
 * @file symbol_NA.ld
 * @author Irdkwia & Adakite
 * @brief SND Stream Library C Edition
 * @details Port of SND Stream Library to C
 * @version 0.9.0
 * @date 2026-08-09
 */
FunctionUnk1 = 0x02002CB4;

SoundMemoryArenaPtr = 0x022A4E54;

EndHookStartBGM = 0x020198D4;
EndHookStartBGM2 = 0x02019970;
EndOfStartBGM = 0x02019AF8;
EndHookStopBGM = 0x02019B34;
EndHookChangeBGM = 0x02019C68;

EndHookStart2BGM = 0x02019DA0;
EndHookStart2BGM2 = 0x02019E3C;
EndOfStart2BGM = 0x02019FB8;
EndHookStop2BGM = 0x02019FF0;
EndHookChange2BGM = 0x0201A100;

HookCheckOverlayArm9 = 0x020B0C80;
EndHookSoundProcess = 0x0207103C;
HookChannel1 = 0x020743EC;
HookChannel2 = 0x020743F4;

EndHookDSEVoiceAllocate = 0x020746A4;
EndHookDSEVoiceAllocateSkip = 0x020746D4;
EndHookDSEVoiceAllocate2 = 0x02074724;
EndHookDSEVoiceAllocateSkip2 = 0x0207473C;

SetChannelVolume = 0x0207CA24;
SetChannelGlobal = 0x0207CA6C;

ChannelsStruct = 0x022B7A30;
VoicesStruct = 0x022B7A6C;

TMR2 = 0x04000108;