/**
 * @file symbol_EU.ld
 * @author Irdkwia & Adakite
 * @brief SND Stream Library C Edition
 * @details Port of SND Stream Library to C
 * @version 0.8.6
 * @date 2026-02-22
 */
FunctionUnk1 = 0x02002CB4;

SoundMemoryArenaPtr = 0x022A5794;

EndHookStartBGM = 0x02019970;
EndHookStartBGM2 = 0x02019A0C;
EndOfStartBGM = 0x02019B94;
EndHookStopBGM = 0x02019BD0;
EndHookChangeBGM = 0x02019D04;

HookCheckOverlayArm9 = 0x020B15C4;
EndHookSoundProcess = 0x020713D4;
HookChannel1 = 0x02074784;
HookChannel2 = 0x0207478C;

SetChannelVolume = 0x0207CDBC;
SetChannelGlobal = 0x0207CE04;

ChannelsStruct = 0x022B8370;

TMR2 = 0x04000108;