/**
 * @file symbol_JP.ld
 * @author Irdkwia & Adakite
 * @brief SND Stream Library C Edition
 * @details Port of SND Stream Library to C
 * @version 0.9.0
 * @date 2026-08-09
 */
FunctionUnk1 = 0x02002CB4;

SoundMemoryArenaPtr = 0x022A66B4;

EndHookStartBGM = 0x0201992C;
EndHookStartBGM2 = 0x020199C8;
EndOfStartBGM = 0x02019B50;
EndHookStopBGM = 0x02019B8C;
EndHookChangeBGM = 0x02019CC0;

EndHookStart2BGM = 0x02019DF8;
EndHookStart2BGM2 = 0x02019E94;
EndOfStart2BGM = 0x0201A010;
EndHookStop2BGM = 0x0201A048;
EndHookChange2BGM = 0x0201A158;

HookCheckOverlayArm9 = 0x020B0C80;
EndHookSoundProcess = 0x02071324;
HookChannel1 = 0x020746D4;
HookChannel2 = 0x020746DC;

EndHookDSEVoiceAllocate = 0x0207498C;
EndHookDSEVoiceAllocateSkip = 0x020749BC;
EndHookDSEVoiceAllocate2 = 0x02074A0C;
EndHookDSEVoiceAllocateSkip2 = 0x02074A24;

SetChannelVolume = 0x0207CD0C;
SetChannelGlobal = 0x0207CD54;

ChannelsStruct = 0x022B91E8;
VoicesStruct = 0x022B9224;

TMR2 = 0x04000108;